sudo: required
language: ruby
node_js:
  - "6.1"
ruby:
  - "2.4.1"
install:
  - chruby 2.4.1
  - npm install -g -y
  - bundle install
script:
  - gherkin-lint ./features/*.feature
  - gherkin_lint ./features/*.feature --disable AvoidScripting,TooLongStep,InvalidStepFlow,BackgroundRequiresMultipleScenarios

